# Generated by Django 2.0.1 on 2018-05-03 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Zip_code', models.IntegerField()),
                ('Number_of_weapons', models.IntegerField()),
                ('Number_of_vehicles', models.IntegerField()),
                ('Number_of_workers', models.IntegerField()),
                ('Head', models.CharField(max_length=255)),
                ('Area', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'verbose_name': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Police_Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, default=800.0, max_digits=8)),
                ('card_number', models.CharField(max_length=255)),
                ('gun_id', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('rank', models.IntegerField()),
                ('working_hours', models.IntegerField()),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pd.Department')),
                ('officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('isComplete', models.BooleanField(default=False)),
                ('Dudate', models.DateField()),
                ('Executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tasks',
                'verbose_name': 'Task',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plate_number', models.CharField(max_length=60)),
                ('Model', models.CharField(max_length=255)),
                ('isInUse', models.BooleanField(default=False)),
                ('BelongsTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pd.Department')),
                ('Using_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pd.Police_Officer')),
            ],
        ),
    ]
