# Generated by Django 2.0.1 on 2018-05-03 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, default=800.0, max_digits=8)),
                ('card_number', models.CharField(max_length=255)),
                ('gun_id', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('rank', models.IntegerField()),
                ('working_hours', models.IntegerField()),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pd.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='police_officer',
            name='dep',
        ),
        migrations.RemoveField(
            model_name='police_officer',
            name='officer',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Using_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pd.UserProfile'),
        ),
        migrations.DeleteModel(
            name='Police_Officer',
        ),
    ]
